"""Update to domain-based structure

Revision ID: f8a76ba9208f
Revises: 2aabd459eda8
Create Date: 2025-03-20 06:01:14.053583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a76ba9208f'
down_revision = '2aabd459eda8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('product_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('product_categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_column('product_categories', 'updated_at')
    op.drop_column('product_categories', 'created_at')
    op.drop_column('product_categories', 'id')
    # ### end Alembic commands ### 